name: SkillsPlugin
version: 1.0.0
main: com.thornily.skills.SkillsPlugin
api-version: 1.21
author: thornily
description: A comprehensive skills system for Minecraft

commands:
  skills:
    description: View your skills
    usage: /skills [player]
    aliases: [skill, sk]
  skillset:
    description: Manage skills (admin)
    usage: /skillset <player> <skill> <level>
    permission: skills.admin
  skillreset:
    description: Reset a player's skills
    usage: /skillreset <player> [skill]
    permission: skills.admin
  query:
    description: Execute database queries (operators only)
    usage: /query <sql>
    permission: skills.admin
  admin-utils:
    description: Admin utilities for spawning items
    usage: /admin-utils spawn <item> [damage]
    aliases: [au, adminutils]
    permission: skills.admin
  stats:
    description: View combat statistics
    usage: /stats [player]
    aliases: [stat, statistics]

permissions:
  skills.use:
    description: Allows using the skills system
    default: true
  skills.view:
    description: Allows viewing own skills
    default: true
  skills.view.others:
    description: Allows viewing other players' skills
    default: op
  skills.admin:
    description: Allows managing skills
    default: op
